import numpy as np
import os
import pyrosim.pyrosim as pyrosim
import random
import time
import constants as c # Make sure constants is imported

class SOLUTION:
    def __init__(self, myID):
        self.myID = myID
        # Initialize weights randomly between -1 and 1
        self.weights = np.random.rand(c.numSensorNeurons, c.numMotorNeurons) * 2 - 1
        self.fitness = 0 # Initialize fitness

    def Start_Simulation(self, mode="DIRECT"):
        # Generate the simulation files specific to this solution
        self.Create_World()
        self.Create_Body()
        self.Create_Brain()
        # Launch the simulation as a background process
        os.system(f"start /B python simulate.py {mode} {self.myID} >nul 2>&1")
        # os.system(f"python simulate.py {mode} {self.myID}") # Use this for foreground/debugging

    # --- UPDATED: Fitness based on Max Height ---
    def Compute_Fitness(self):
        """Calculates fitness based on maximum Z-position achieved."""
        filename = f"z_pos{self.myID}.npy" # Load the Z-position file

        try:
            z_positions = np.load(filename)

            # --- Fitness is Maximum Height ---
            if z_positions.size > 0:
                # Fitness is the highest Z-coordinate reached by the base link
                self.fitness = np.max(z_positions)
                # Optional: Subtract initial height if you want height *gain*
                # initial_height = z_positions[0] # Or a known constant like 1.0
                # self.fitness = np.max(z_positions) - initial_height
            else:
                print(f"Warning: Z-position data file {filename} is empty. Fitness set to 0.")
                self.fitness = 0 # Assign 0 fitness if no data points

        except FileNotFoundError:
            # This case should ideally be caught by Wait_For_Simulation_To_End timeout
            print(f"ERROR: Fitness Calc - Z-position file not found: {filename}. Fitness set to 0.")
            self.fitness = 0
            return # Exit if file doesn't exist
        except Exception as e:
            print(f"ERROR: Fitness Calc - Could not load/process Z-position file {filename}: {e}. Fitness set to 0.")
            self.fitness = 0
            return

        # Final fitness print for this solution
        print(f"Computed Max Height fitness for solution {self.myID}: {self.fitness}")
    # --- End Updated Fitness Calculation ---


    # --- UPDATED: Wait for Z-position file ---
    def Wait_For_Simulation_To_End(self):
        """Waits for the Z-position data file generated by the simulation."""
        filename = f"z_pos{self.myID}.npy" # Wait for the Z-position file
        print(f"Waiting for Z-position file: {filename}")

        timeout = 10.0 # seconds (adjust if simulations take longer)
        start_time = time.time()
        while not os.path.exists(filename):
            if time.time() - start_time > timeout:
                print(f"ERROR: Timeout waiting for Z-position file {filename}")
                self.fitness = 0 # Assign low fitness on timeout
                return # Exit waiting if timeout occurs
            time.sleep(0.1)

        # File exists, proceed with fitness calculation
        if os.path.exists(filename):
            try:
                # Compute fitness using the new Z-position data
                self.Compute_Fitness() # Call the renamed fitness function

                # Remove the Z-position file *after* computing fitness
                os.remove(filename)
                # print(f"Z-position file removed: {filename}") # Optional print
            except Exception as e:
                 print(f"ERROR: Failed during fitness computation or file removal for {filename}: {e}")
                 self.fitness = 0 # Assign low fitness on error
        else:
            # Fallback if timeout failed or file disappeared
            print(f"No Z-position file found after wait loop for {filename}; fitness not computed.")
            self.fitness = 0
    # --- End Updated Wait Function ---


    def Mutate(self):
        # Simple mutation: change one random weight
        randomRow = random.randint(0, c.numSensorNeurons - 1)
        randomCol = random.randint(0, c.numMotorNeurons - 1)
        self.weights[randomRow, randomCol] = random.uniform(-1, 1)

    def Create_World(self):
        # Generates world.sdf
        pyrosim.Start_SDF("world.sdf")
        pyrosim.Send_Cube(name="Box", pos=[-5, 0, 0.5], size=[1, 1, 1])
        pyrosim.End()

    def Create_Body(self):
        # Generates body.urdf - includes the fix for lower leg position
        pyrosim.Start_URDF("body.urdf")
        # Torso
        pyrosim.Send_Cube(name="Torso", pos=[0, 0, 1], size=[1, 1, 1])
        # --- Upper Legs ---
        pyrosim.Send_Joint(name="Torso_BackLeg", parent="Torso", child="BackLeg", type="revolute", position=[0, -0.5, 1], jointAxis="1 0 0")
        pyrosim.Send_Cube(name="BackLeg", pos=[0, -0.5, 0], size=[0.2, 1, 0.2])
        pyrosim.Send_Joint(name="Torso_FrontLeg", parent="Torso", child="FrontLeg", type="revolute", position=[0, 0.5, 1], jointAxis="1 0 0")
        pyrosim.Send_Cube(name="FrontLeg", pos=[0, 0.5, 0], size=[0.2, 1, 0.2])
        pyrosim.Send_Joint(name="Torso_LeftLeg", parent="Torso", child="LeftLeg", type="revolute", position=[-0.5, 0, 1], jointAxis="0 1 0")
        pyrosim.Send_Cube(name="LeftLeg", pos=[-0.5, 0, 0], size=[1, 0.2, 0.2])
        pyrosim.Send_Joint(name="Torso_RightLeg", parent="Torso", child="RightLeg", type="revolute", position=[0.5, 0, 1], jointAxis="0 1 0")
        pyrosim.Send_Cube(name="RightLeg", pos=[0.5, 0, 0], size=[1, 0.2, 0.2])
        # --- Lower Legs (with Z pos fix) ---
        pyrosim.Send_Joint(name="Torso_FrontLowerLeg", parent="FrontLeg", child="FrontLowerLeg", type="revolute", position=[0, 1, 0], jointAxis="1 0 0")
        pyrosim.Send_Cube(name="FrontLowerLeg", pos=[0, 0, -0.51], size=[0.2, 0.2, 1]) # Z pos fix
        pyrosim.Send_Joint(name="Torso_BackLowerLeg", parent="BackLeg", child="BackLowerLeg", type="revolute", position=[0, -1, 0], jointAxis="1 0 0")
        pyrosim.Send_Cube(name="BackLowerLeg", pos=[0, 0, -0.51], size=[0.2, 0.2, 1]) # Z pos fix
        pyrosim.Send_Joint(name="Torso_LeftLowerLeg", parent="LeftLeg", child="LeftLowerLeg", type="revolute", position=[-1, 0, 0], jointAxis="0 1 0")
        pyrosim.Send_Cube(name="LeftLowerLeg", pos=[0, 0, -0.51], size=[0.2, 0.2, 1]) # Z pos fix
        pyrosim.Send_Joint(name="Torso_RightLowerLeg", parent="RightLeg", child="RightLowerLeg", type="revolute", position=[1, 0, 0], jointAxis="0 1 0")
        pyrosim.Send_Cube(name="RightLowerLeg", pos=[0, 0, -0.51], size=[0.2, 0.2, 1]) # Z pos fix
        pyrosim.End()

    def Create_Brain(self):
        # Generates brain<ID>.nndf
        pyrosim.Start_NeuralNetwork("brain" + str(self.myID) + ".nndf")
        # Sensors (Indices 0-8)
        pyrosim.Send_Sensor_Neuron(name=0, linkName="Torso")
        pyrosim.Send_Sensor_Neuron(name=1, linkName="BackLeg")
        pyrosim.Send_Sensor_Neuron(name=2, linkName="FrontLeg")
        pyrosim.Send_Sensor_Neuron(name=3, linkName="LeftLeg")
        pyrosim.Send_Sensor_Neuron(name=4, linkName="RightLeg")
        pyrosim.Send_Sensor_Neuron(name=5, linkName="FrontLowerLeg")
        pyrosim.Send_Sensor_Neuron(name=6, linkName="BackLowerLeg")
        pyrosim.Send_Sensor_Neuron(name=7, linkName="LeftLowerLeg")
        pyrosim.Send_Sensor_Neuron(name=8, linkName="RightLowerLeg")
        # Motors (Indices 9-16)
        pyrosim.Send_Motor_Neuron(name=c.numSensorNeurons + 0, jointName="Torso_BackLeg")
        pyrosim.Send_Motor_Neuron(name=c.numSensorNeurons + 1, jointName="Torso_FrontLeg")
        pyrosim.Send_Motor_Neuron(name=c.numSensorNeurons + 2, jointName="Torso_LeftLeg")
        pyrosim.Send_Motor_Neuron(name=c.numSensorNeurons + 3, jointName="Torso_RightLeg")
        pyrosim.Send_Motor_Neuron(name=c.numSensorNeurons + 4, jointName="Torso_FrontLowerLeg")
        pyrosim.Send_Motor_Neuron(name=c.numSensorNeurons + 5, jointName="Torso_BackLowerLeg")
        pyrosim.Send_Motor_Neuron(name=c.numSensorNeurons + 6, jointName="Torso_LeftLowerLeg")
        pyrosim.Send_Motor_Neuron(name=c.numSensorNeurons + 7, jointName="Torso_RightLowerLeg")
        # Synapses
        for curRow in range(c.numSensorNeurons):
            for curCol in range(c.numMotorNeurons):
                pyrosim.Send_Synapse(sourceNeuronName=curRow,
                                     targetNeuronName=curCol + c.numSensorNeurons,
                                     weight=self.weights[curRow][curCol])
        pyrosim.End()

    def Set_ID(self, newID):
        # Allows changing the ID, used by Spawn in parallelHillClimber
        self.myID = newID
